### ISSUE TITLE
Can't start by 'node --harmony MongoNoteServer'

### ISSUE THREAD

**Issue by gogobook** [cccunimportant/MongoNoteServer#1]
``` sh
module.js:338
    throw err;
          ^
Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/mysandbox/myMongoNoteServer/MongoNoteServer/MongoNoteServer.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

The version of node.js is 0.12.7
Is MongoNoteServer only for iojs?

**Comment by gogobook** [comment]
There is no "co" and "monk" module in package.json
